from typing import Protocol


class ProjectRepository(Protocol):
    def create(self, document: dict) -> None: ...
    def get(self, project_id: str) -> dict | None: ...
    def list_projects(self) -> list[dict]: ...
    def append_message(self, project_id: str, message: dict) -> None: ...
    def set_workspace(self, project_id: str, workspace: dict) -> None: ...
    def update_context(self, project_id: str, context: dict) -> None: ...
    def set_last_run(self, project_id: str, run_id: str) -> None: ...
