"""Ports de persistência - um Protocol por agregado (ISP: quem só precisa
gravar mensagens não recebe a capacidade de apagar runs)."""
from __future__ import annotations

from typing import Protocol

from ..entities.adr import ADR
from ..entities.agent_message import AgentMessage
from ..entities.artifact import Artifact
from ..entities.run import Run
from ..entities.story import Story
from ..entities.test_report import TestReport


class RunRepository(Protocol):
    async def save(self, run: Run) -> None: ...
    async def get(self, run_id: str) -> Run | None: ...
    async def list_recent(self, limit: int = 20) -> list[Run]: ...


class StoryRepository(Protocol):
    async def save_many(self, stories: list[Story]) -> None: ...
    async def update_status(self, story_id: str, status: str) -> None: ...
    async def list_by_run(self, run_id: str) -> list[Story]: ...


class MessageRepository(Protocol):
    async def append(self, message: AgentMessage) -> None: ...
    async def list_by_run(self, run_id: str) -> list[AgentMessage]: ...
    async def next_seq(self, run_id: str) -> int: ...


class ArtifactRepository(Protocol):
    async def append(self, artifact: Artifact) -> None: ...
    async def list_by_run(self, run_id: str) -> list[Artifact]: ...


class ADRRepository(Protocol):
    async def append(self, adr: ADR) -> None: ...
    async def list_by_run(self, run_id: str) -> list[ADR]: ...


class TestReportRepository(Protocol):
    async def append(self, report: TestReport) -> None: ...
    async def list_by_run(self, run_id: str) -> list[TestReport]: ...
