from pathlib import Path
from typing import Protocol


class WorkspaceManager(Protocol):
    def create_project(self, run_id: str, project_name: str) -> dict: ...
    def open_project_workspace(self, workspace: dict) -> dict: ...
    def template_manifest(self) -> str: ...
    def code_tree(self, workspace: dict) -> list[str]: ...
    def read_code(self, workspace: dict, path: str) -> str: ...
    def write_code(self, workspace: dict, path: str, content: str) -> Path: ...
    def delete_code(self, workspace: dict, path: str) -> None: ...
    def diff(self, workspace: dict) -> str: ...
    def write_artifact(self, workspace: dict, filename: str, content: str) -> Path: ...
