from __future__ import annotations

from collections.abc import Callable, Iterator
from typing import Protocol

from fullstack_agents.domain.models import LLMRequest, LLMStreamEvent, ProductBacklog


class RunRepository(Protocol):
    def create(self, document: dict) -> None: ...
    def get(self, run_id: str) -> dict | None: ...
    def mark_running(self, run_id: str) -> None: ...
    def reserve_sequence(self, run_id: str) -> int: ...
    def append_timeline(self, run_id: str, item: dict) -> None: ...
    def update_streaming_response(self, run_id: str, call_id: str, content: str) -> None: ...
    def finish_call(self, run_id: str, call_id: str, fields: dict) -> None: ...
    def finish_run(self, run_id: str, output: ProductBacklog, totals: dict) -> None: ...
    def fail_run(self, run_id: str, error: str) -> None: ...


class StreamingLLM(Protocol):
    provider: str
    model: str

    def stream(self, request: LLMRequest) -> Iterator[LLMStreamEvent]: ...


StreamObserver = Callable[[str], None]
