services:
  mongo:
    image: mongo:7
    container_name: squad_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - squad_mongo_data:/data/db

volumes:
  squad_mongo_data:
