"""Templates used by the deterministic pipeline demo mode."""
from __future__ import annotations

from pathlib import Path


BACKLOG = [
    {
        "id": "US-01",
        "title": "Registro agil de nao conformidade",
        "description": "Como operador, quero registrar defeitos pelo celular com evidencias auditaveis.",
        "priority": "alta",
        "acceptance_criteria": [
            "Formulario responsivo com descricao, lote, responsavel, turno, equipamento e linha.",
            "Registro salvo com data, responsavel, turno e equipamento.",
        ],
    },
    {
        "id": "US-02",
        "title": "Causa raiz assistida",
        "description": "Como qualidade, quero sugestoes e plano de acao a partir do historico.",
        "priority": "alta",
        "acceptance_criteria": [
            "Analise com 5 porques, causas sugeridas e plano de acao.",
            "Sugestoes usam historico local semeado.",
        ],
    },
    {
        "id": "US-03",
        "title": "Rastreabilidade de lote",
        "description": "Como coordenador, quero consultar lote e ver toda a cadeia produtiva.",
        "priority": "alta",
        "acceptance_criteria": [
            "Consulta LOTE-4521 retorna materia-prima, fornecedor, equipamento, turno, operadores e correlatos.",
            "Lote inexistente retorna erro claro.",
        ],
    },
]


FILES = {
    "README.md": """# Rivexx Qualidade

Projeto gerado pelo pipeline de agentes em modo simples.

## Rodar

```bash
cd code/app
python -m backend.app --port 8000
```

Acesse `http://127.0.0.1:8000`.

## Testes

```bash
cd code/app/backend
python -m unittest -q
```
""",
    "backend/__init__.py": '"""Backend package."""\n',
    "backend/app.py": '''"""Minimal Rivexx backend generated by the pipeline."""
from __future__ import annotations

import argparse
import json
from copy import deepcopy
from datetime import datetime, timezone
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import unquote, urlparse

ROOT = Path(__file__).resolve().parents[1]
FRONTEND = ROOT / "frontend"

NONCONFORMITIES = [
    {
        "id": "NC-1001",
        "created_at": "2026-08-22T08:20:00Z",
        "description": "Defeito dimensional na linha 4.",
        "lot_code": "LOTE-4521",
        "responsible": "Carla Mendes",
        "shift": "B",
        "equipment": "INJ-04",
        "line": "Linha 4",
    },
    {
        "id": "NC-1002",
        "created_at": "2026-08-21T19:05:00Z",
        "description": "Variacao dimensional apos troca de molde.",
        "lot_code": "LOTE-4519",
        "responsible": "Rafael Nogueira",
        "shift": "C",
        "equipment": "INJ-04",
        "line": "Linha 4",
    },
]

LOTS = {
    "LOTE-4521": {
        "lot_code": "LOTE-4521",
        "raw_material": "PA66 GF30 - MP-88A-26",
        "supplier": "Polimix Resinas",
        "equipment": "INJ-04",
        "shift": "B",
        "operators": ["Carla Mendes", "Joao Ribeiro"],
        "correlated_lots": ["LOTE-4519", "LOTE-4520"],
        "shipments": ["AutoParts Sul - NF-88321", "EletroMaq - NF-88324"],
    },
    "LOTE-4519": {
        "lot_code": "LOTE-4519",
        "raw_material": "PA66 GF30 - MP-88A-25",
        "supplier": "Polimix Resinas",
        "equipment": "INJ-04",
        "shift": "C",
        "operators": ["Rafael Nogueira", "Bianca Torres"],
        "correlated_lots": ["LOTE-4521"],
        "shipments": ["AutoParts Sul - NF-88270"],
    },
}

NEXT_ID = 1003


def list_nonconformities():
    return deepcopy(NONCONFORMITIES)


def create_nonconformity(payload):
    global NEXT_ID
    required = ["description", "lot_code", "responsible", "shift", "equipment", "line"]
    missing = [field for field in required if not str(payload.get(field, "")).strip()]
    if missing:
        raise ValueError("Campos obrigatorios: " + ", ".join(missing))
    item = {
        "id": f"NC-{NEXT_ID}",
        "created_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z"),
        "description": payload["description"].strip(),
        "lot_code": payload["lot_code"].strip().upper(),
        "responsible": payload["responsible"].strip(),
        "shift": payload["shift"].strip().upper(),
        "equipment": payload["equipment"].strip().upper(),
        "line": payload["line"].strip() if payload["line"].lower().startswith("linha") else f"Linha {payload['line'].strip()}",
    }
    NEXT_ID += 1
    NONCONFORMITIES.insert(0, item)
    return deepcopy(item)


def analyze_root_cause(record_id):
    record = next((item for item in NONCONFORMITIES if item["id"] == record_id), None)
    if not record:
        raise KeyError("Registro nao encontrado.")
    related = [
        item for item in NONCONFORMITIES
        if item["id"] != record_id and (item["equipment"] == record["equipment"] or item["line"] == record["line"])
    ]
    cause = f"Setup ou desgaste de molde no {record['equipment']}"
    return {
        "record": deepcopy(record),
        "suggested_causes": [
            {"cause": cause, "evidence": f"{len(related)} registro(s) similar(es) no historico."},
            {"cause": "Variacao de materia-prima afetando contracao da peca", "evidence": "Lotes correlatos usam a mesma familia de material."},
        ],
        "five_whys": [
            "Defeito dimensional detectado na inspecao.",
            cause,
            "Parametros de processo podem ter variado sem contencao imediata.",
            "Historico mostra recorrencia no mesmo equipamento/linha.",
            "Revisar setup, bloquear lote e acompanhar eficacia por 7 dias.",
        ],
        "action_plan": [
            {"action": f"Bloquear {record['lot_code']} ate triagem.", "owner": "Qualidade", "due": "Hoje", "status": "Aberta"},
            {"action": f"Revalidar setup do {record['equipment']}.", "owner": "Processos", "due": "24h", "status": "Aberta"},
            {"action": "Medir lotes correlatos.", "owner": "Laboratorio", "due": "48h", "status": "Aberta"},
        ],
    }


def trace_lot(lot_code):
    key = str(lot_code).strip().upper()
    if key not in LOTS:
        raise KeyError(f"Lote nao encontrado: {key}")
    return deepcopy(LOTS[key])


class Handler(BaseHTTPRequestHandler):
    def do_GET(self):
        try:
            path = urlparse(self.path).path
            if path == "/api/health":
                self.json({"status": "ok"})
            elif path == "/api/nonconformities":
                self.json({"items": list_nonconformities()})
            elif path.startswith("/api/root-cause/"):
                self.json(analyze_root_cause(unquote(path.rsplit("/", 1)[-1])))
            elif path.startswith("/api/traceability/"):
                self.json(trace_lot(unquote(path.rsplit("/", 1)[-1])))
            else:
                self.static(path)
        except ValueError as exc:
            self.json({"error": str(exc)}, HTTPStatus.BAD_REQUEST)
        except KeyError as exc:
            self.json({"error": str(exc).strip("'")}, HTTPStatus.NOT_FOUND)

    def do_POST(self):
        try:
            if urlparse(self.path).path != "/api/nonconformities":
                self.json({"error": "Rota nao encontrada."}, HTTPStatus.NOT_FOUND)
                return
            length = int(self.headers.get("Content-Length", "0"))
            payload = json.loads(self.rfile.read(length).decode("utf-8"))
            self.json(create_nonconformity(payload), HTTPStatus.CREATED)
        except ValueError as exc:
            self.json({"error": str(exc)}, HTTPStatus.BAD_REQUEST)

    def static(self, path):
        target = FRONTEND / ("index.html" if path in ("", "/") else path.lstrip("/"))
        if not target.exists():
            self.json({"error": "Arquivo nao encontrado."}, HTTPStatus.NOT_FOUND)
            return
        content_type = "text/css" if target.suffix == ".css" else "application/javascript" if target.suffix == ".js" else "text/html"
        body = target.read_bytes()
        self.send_response(HTTPStatus.OK)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def json(self, data, status=HTTPStatus.OK):
        body = json.dumps(data, ensure_ascii=False).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--port", type=int, default=8000)
    args = parser.parse_args()
    server = ThreadingHTTPServer(("127.0.0.1", args.port), Handler)
    print(f"Rivexx rodando em http://127.0.0.1:{args.port}")
    server.serve_forever()


if __name__ == "__main__":
    main()
''',
    "backend/test_app.py": '''import unittest

import app


class RivexxTest(unittest.TestCase):
    def test_create_nonconformity_requires_audit_fields(self):
        with self.assertRaises(ValueError):
            app.create_nonconformity({"description": "x"})

    def test_create_nonconformity_saves_record(self):
        item = app.create_nonconformity({
            "description": "Defeito dimensional",
            "lot_code": "lote-4521",
            "responsible": "Teste",
            "shift": "b",
            "equipment": "inj-04",
            "line": "4",
        })
        self.assertEqual(item["lot_code"], "LOTE-4521")
        self.assertEqual(item["equipment"], "INJ-04")

    def test_root_cause_has_five_whys_and_action_plan(self):
        result = app.analyze_root_cause("NC-1001")
        self.assertEqual(len(result["five_whys"]), 5)
        self.assertEqual(len(result["action_plan"]), 3)
        self.assertIn("INJ-04", result["suggested_causes"][0]["cause"])

    def test_trace_lot_returns_chain(self):
        lot = app.trace_lot("lote-4521")
        self.assertEqual(lot["supplier"], "Polimix Resinas")
        self.assertEqual(lot["equipment"], "INJ-04")
        self.assertIn("Carla Mendes", lot["operators"])
        self.assertIn("LOTE-4519", lot["correlated_lots"])


if __name__ == "__main__":
    unittest.main()
''',
    "frontend/index.html": '''<!doctype html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Rivexx Qualidade</title>
    <link rel="stylesheet" href="/style.css" />
  </head>
  <body>
    <main class="shell">
      <header>
        <p>Rivexx Componentes</p>
        <h1>Qualidade e rastreabilidade</h1>
      </header>
      <nav>
        <button data-tab="registro">Registro</button>
        <button data-tab="causa">Causa raiz</button>
        <button data-tab="lote">Rastreabilidade</button>
      </nav>
      <section id="registro" class="tab active">
        <form id="form">
          <textarea name="description" required>Defeito dimensional na linha 4.</textarea>
          <input name="lot_code" value="LOTE-4521" required />
          <input name="responsible" value="Carla Mendes" required />
          <select name="shift"><option>B</option><option>A</option><option>C</option></select>
          <input name="equipment" value="INJ-04" required />
          <input name="line" value="4" required />
          <button type="submit">Registrar</button>
        </form>
        <p id="message"></p>
        <div id="records"></div>
      </section>
      <section id="causa" class="tab">
        <select id="recordSelect"></select>
        <div id="analysis"></div>
      </section>
      <section id="lote" class="tab">
        <form id="lotForm"><input name="lot" value="LOTE-4521" /><button>Consultar</button></form>
        <div id="trace"></div>
      </section>
    </main>
    <script src="/app.js"></script>
  </body>
</html>
''',
    "frontend/style.css": '''body{margin:0;background:#f3f6f4;color:#17251f;font-family:Arial,sans-serif}.shell{width:min(960px,calc(100% - 24px));margin:auto;padding:20px}header{display:flex;justify-content:space-between;gap:16px;align-items:end}header p{color:#0f766e;font-weight:700;text-transform:uppercase}h1{font-size:clamp(1.5rem,4vw,2.3rem)}nav{display:flex;gap:8px;overflow:auto;margin:16px 0}button{border:0;border-radius:8px;background:#0f766e;color:white;font-weight:700;padding:11px 14px}input,select,textarea{width:100%;box-sizing:border-box;border:1px solid #cfd9d3;border-radius:8px;padding:10px;margin:6px 0 10px;background:white}textarea{min-height:90px}.tab{display:none;background:white;border:1px solid #d8e0db;border-radius:8px;padding:16px}.tab.active{display:block}.card{border:1px solid #d8e0db;border-radius:8px;padding:12px;margin:10px 0;background:#fbfcfb}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px}@media(max-width:520px){header{display:block}.shell{width:calc(100% - 16px);padding:8px}nav button{min-width:120px}}''',
    "frontend/app.js": '''const $=s=>document.querySelector(s);const esc=s=>String(s??"").replace(/[&<>]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]));
async function api(path,opt){const r=await fetch(path,{headers:{"Content-Type":"application/json"},...opt});const d=await r.json();if(!r.ok)throw Error(d.error);return d}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(t=>t.classList.remove("active"));$("#"+b.dataset.tab).classList.add("active")});
async function loadRecords(){const d=await api("/api/nonconformities");$("#records").innerHTML=d.items.map(r=>`<div class=card><b>${esc(r.id)} - ${esc(r.lot_code)}</b><p>${esc(r.description)}</p><small>${esc(r.created_at)} | ${esc(r.responsible)} | ${esc(r.shift)} | ${esc(r.equipment)} | ${esc(r.line)}</small></div>`).join("");$("#recordSelect").innerHTML=d.items.map(r=>`<option>${esc(r.id)}</option>`).join("");if(d.items[0])loadCause(d.items[0].id)}
async function loadCause(id){const d=await api("/api/root-cause/"+encodeURIComponent(id));$("#analysis").innerHTML=`<h2>5 porques</h2>${d.five_whys.map(x=>`<div class=card>${esc(x)}</div>`).join("")}<h2>Causas sugeridas</h2>${d.suggested_causes.map(x=>`<div class=card><b>${esc(x.cause)}</b><p>${esc(x.evidence)}</p></div>`).join("")}<h2>Plano</h2><div class=grid>${d.action_plan.map(x=>`<div class=card><b>${esc(x.action)}</b><p>${esc(x.owner)} | ${esc(x.due)} | ${esc(x.status)}</p></div>`).join("")}</div>`}
$("#form").onsubmit=async e=>{e.preventDefault();try{const d=await api("/api/nonconformities",{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});$("#message").textContent=d.id+" registrado.";await loadRecords()}catch(err){$("#message").textContent=err.message}};
$("#recordSelect").onchange=e=>loadCause(e.target.value);
$("#lotForm").onsubmit=async e=>{e.preventDefault();try{const d=await api("/api/traceability/"+encodeURIComponent(new FormData(e.target).get("lot")));$("#trace").innerHTML=`<div class=card><b>${esc(d.lot_code)}</b><p>${esc(d.raw_material)} | ${esc(d.supplier)}</p><p>${esc(d.equipment)} | turno ${esc(d.shift)} | ${d.operators.map(esc).join(", ")}</p><p>Correlatos: ${d.correlated_lots.map(esc).join(", ")}</p><p>Expedicao: ${d.shipments.map(esc).join(", ")}</p></div>`}catch(err){$("#trace").innerHTML=`<div class=card>${esc(err.message)}</div>`}};
loadRecords();$("#lotForm").dispatchEvent(new Event("submit"));
''',
}


def _load_template_files() -> dict[str, str]:
    template_root = Path(__file__).resolve().parent / "simple_templates"
    if not template_root.exists():
        return FILES
    loaded = dict(FILES)
    for path in template_root.rglob("*"):
        if "__pycache__" in path.parts or path.suffix == ".pyc":
            continue
        if path.is_file():
            loaded[str(path.relative_to(template_root)).replace("\\", "/")] = path.read_text(encoding="utf-8")
    return loaded


FILES = _load_template_files()
