"""Minimal Rivexx backend generated by the pipeline."""
from __future__ import annotations

import argparse
import json
from copy import deepcopy
from datetime import datetime, timezone
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import unquote, urlparse

ROOT = Path(__file__).resolve().parents[1]
FRONTEND = ROOT / "frontend"
CODE_ROOT = ROOT.parent
DEFAULT_BRIEF_PATH = CODE_ROOT / "pipeline" / "briefs" / "rivexx.txt"

NONCONFORMITIES = [
    {
        "id": "NC-1001",
        "created_at": "2026-08-22T08:20:00Z",
        "description": "Defeito dimensional na linha 4.",
        "lot_code": "LOTE-4521",
        "responsible": "Carla Mendes",
        "shift": "B",
        "equipment": "INJ-04",
        "line": "Linha 4",
    },
    {
        "id": "NC-1002",
        "created_at": "2026-08-21T19:05:00Z",
        "description": "Variacao dimensional apos troca de molde.",
        "lot_code": "LOTE-4519",
        "responsible": "Rafael Nogueira",
        "shift": "C",
        "equipment": "INJ-04",
        "line": "Linha 4",
    },
]

LOTS = {
    "LOTE-4521": {
        "lot_code": "LOTE-4521",
        "raw_material": "PA66 GF30 - MP-88A-26",
        "supplier": "Polimix Resinas",
        "equipment": "INJ-04",
        "shift": "B",
        "operators": ["Carla Mendes", "Joao Ribeiro"],
        "correlated_lots": ["LOTE-4519", "LOTE-4520"],
        "shipments": ["AutoParts Sul - NF-88321", "EletroMaq - NF-88324"],
    },
    "LOTE-4519": {
        "lot_code": "LOTE-4519",
        "raw_material": "PA66 GF30 - MP-88A-25",
        "supplier": "Polimix Resinas",
        "equipment": "INJ-04",
        "shift": "C",
        "operators": ["Rafael Nogueira", "Bianca Torres"],
        "correlated_lots": ["LOTE-4521"],
        "shipments": ["AutoParts Sul - NF-88270"],
    },
}

NEXT_ID = 1003
LAST_SQUAD_RUN = None

SQUAD_BACKLOG = [
    {
        "id": "US-01",
        "title": "Registro agil de nao conformidade",
        "description": "Como operador, quero registrar defeitos pelo celular com evidencias auditaveis.",
        "priority": "alta",
        "acceptance_criteria": [
            "Formulario responsivo com descricao, lote, responsavel, turno, equipamento e linha.",
            "Registro salvo com data, responsavel, turno e equipamento.",
            "Listagem mostra o registro sem recarregar a aplicacao.",
        ],
    },
    {
        "id": "US-02",
        "title": "Causa raiz assistida",
        "description": "Como qualidade, quero sugestoes e plano de acao a partir do historico.",
        "priority": "alta",
        "acceptance_criteria": [
            "Analise apresenta 5 porques, causas sugeridas e evidencias do historico.",
            "Plano de acao contem acao, responsavel, prazo e status.",
        ],
    },
    {
        "id": "US-03",
        "title": "Rastreabilidade de lote",
        "description": "Como coordenador, quero consultar lote e ver toda a cadeia produtiva.",
        "priority": "alta",
        "acceptance_criteria": [
            "Consulta LOTE-4521 retorna materia-prima, fornecedor, equipamento, turno e operadores.",
            "Consulta apresenta lotes correlatos e expedicoes.",
            "Lote inexistente retorna erro claro.",
        ],
    },
]


def list_nonconformities():
    return deepcopy(NONCONFORMITIES)


def create_nonconformity(payload):
    global NEXT_ID
    required = ["description", "lot_code", "responsible", "shift", "equipment", "line"]
    missing = [field for field in required if not str(payload.get(field, "")).strip()]
    if missing:
        raise ValueError("Campos obrigatorios: " + ", ".join(missing))
    item = {
        "id": f"NC-{NEXT_ID}",
        "created_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z"),
        "description": payload["description"].strip(),
        "lot_code": payload["lot_code"].strip().upper(),
        "responsible": payload["responsible"].strip(),
        "shift": payload["shift"].strip().upper(),
        "equipment": payload["equipment"].strip().upper(),
        "line": payload["line"].strip() if payload["line"].lower().startswith("linha") else f"Linha {payload['line'].strip()}",
    }
    NEXT_ID += 1
    NONCONFORMITIES.insert(0, item)
    return deepcopy(item)


def analyze_root_cause(record_id):
    record = next((item for item in NONCONFORMITIES if item["id"] == record_id), None)
    if not record:
        raise KeyError("Registro nao encontrado.")
    related = [
        item for item in NONCONFORMITIES
        if item["id"] != record_id and (item["equipment"] == record["equipment"] or item["line"] == record["line"])
    ]
    cause = f"Setup ou desgaste de molde no {record['equipment']}"
    return {
        "record": deepcopy(record),
        "suggested_causes": [
            {"cause": cause, "evidence": f"{len(related)} registro(s) similar(es) no historico."},
            {"cause": "Variacao de materia-prima afetando contracao da peca", "evidence": "Lotes correlatos usam a mesma familia de material."},
        ],
        "five_whys": [
            "Defeito dimensional detectado na inspecao.",
            cause,
            "Parametros de processo podem ter variado sem contencao imediata.",
            "Historico mostra recorrencia no mesmo equipamento/linha.",
            "Revisar setup, bloquear lote e acompanhar eficacia por 7 dias.",
        ],
        "action_plan": [
            {"action": f"Bloquear {record['lot_code']} ate triagem.", "owner": "Qualidade", "due": "Hoje", "status": "Aberta"},
            {"action": f"Revalidar setup do {record['equipment']}.", "owner": "Processos", "due": "24h", "status": "Aberta"},
            {"action": "Medir lotes correlatos.", "owner": "Laboratorio", "due": "48h", "status": "Aberta"},
        ],
    }


def trace_lot(lot_code):
    key = str(lot_code).strip().upper()
    if key not in LOTS:
        raise KeyError(f"Lote nao encontrado: {key}")
    return deepcopy(LOTS[key])


def default_briefing():
    try:
        return DEFAULT_BRIEF_PATH.read_text(encoding="utf-8")
    except OSError:
        return "Empresa: Rivexx Componentes. Aplicacao web interna para qualidade e rastreabilidade."


def run_squad_observability(brief):
    global LAST_SQUAD_RUN
    text = str(brief or "").strip()
    if not text:
        raise ValueError("Informe um briefing para iniciar o squad.")
    started_at = datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    excerpt = " ".join(text.split())[:220]
    enriched = (
        "Brief tecnico enriquecido: aplicacao interna responsiva para a Rivexx, com foco em registro "
        "auditavel, investigacao estruturada e rastreabilidade rapida de lotes. Arquitetura simples: "
        "backend Python puro, frontend estatico e dados em memoria para demo local."
    )
    decision_log = [
        {"story_id": "US-01", "summary": "Criado fluxo de registro com API, validacao e listagem.", "rationale": "Campos auditaveis ficam juntos no mesmo registro.", "files_changed": ["backend/app.py", "frontend/index.html", "frontend/app.js"], "tests_written": ["backend/test_app.py"]},
        {"story_id": "US-02", "summary": "Criada analise de causa raiz com 5 porques e plano corretivo.", "rationale": "Regras simples baseadas em historico local mantem a demo auditavel.", "files_changed": ["backend/app.py", "frontend/app.js"], "tests_written": ["backend/test_app.py"]},
        {"story_id": "US-03", "summary": "Criada consulta de rastreabilidade para lotes semeados.", "rationale": "Dados locais cobrem a cadeia produtiva obrigatoria.", "files_changed": ["backend/app.py", "frontend/app.js"], "tests_written": ["backend/test_app.py"]},
    ]
    qa_report = [
        {"story_id": "US-01", "approved": True, "test_cases": [{"name": "Campos obrigatorios", "result": "pass", "notes": "Payload incompleto gera erro claro."}], "evidence": "Teste de criacao e auditoria passou.", "feedback": "Aprovado."},
        {"story_id": "US-02", "approved": True, "test_cases": [{"name": "5 porques e plano", "result": "pass", "notes": "Analise retorna 5 respostas e 3 acoes."}], "evidence": "Teste de causa raiz passou.", "feedback": "Aprovado."},
        {"story_id": "US-03", "approved": True, "test_cases": [{"name": "LOTE-4521", "result": "pass", "notes": "Retorna fornecedor, equipamento, operadores e correlatos."}], "evidence": "Teste de rastreabilidade passou.", "feedback": "Aprovado."},
    ]
    communication_log = [
        {"from_agent": "Analyst Agent", "to_agent": "PO Agent", "content": enriched},
        {"from_agent": "PO Agent", "to_agent": "Dev Agent", "content": "Backlog priorizado em 3 stories para a demo obrigatoria."},
        {"from_agent": "Dev Agent", "to_agent": "QA Agent", "content": decision_log[0]["summary"]},
        {"from_agent": "QA Agent", "to_agent": "PO Agent", "content": "US-01 aprovada com evidencias de aceite."},
        {"from_agent": "Dev Agent", "to_agent": "QA Agent", "content": decision_log[1]["summary"]},
        {"from_agent": "QA Agent", "to_agent": "PO Agent", "content": "US-02 aprovada com plano corretivo validado."},
        {"from_agent": "Dev Agent", "to_agent": "QA Agent", "content": decision_log[2]["summary"]},
        {"from_agent": "QA Agent", "to_agent": "PO Agent", "content": "US-03 aprovada com cadeia de lote validada."},
    ]
    LAST_SQUAD_RUN = {
        "run_id": started_at.replace(":", "").replace("-", ""),
        "started_at": started_at,
        "status": "done",
        "brief_excerpt": excerpt,
        "enriched_brief": enriched,
        "backlog": deepcopy(SQUAD_BACKLOG),
        "decision_log": decision_log,
        "qa_report": qa_report,
        "communication_log": communication_log,
        "timeline": [
            {"step": 1, "agent": "Briefing", "status": "received", "detail": excerpt},
            {"step": 2, "agent": "Analyst Agent", "status": "done", "detail": "Escopo tecnico consolidado."},
            {"step": 3, "agent": "PO Agent", "status": "done", "detail": "Stories priorizadas."},
            {"step": 4, "agent": "Dev Agent", "status": "done", "detail": "Codigo implementado."},
            {"step": 5, "agent": "QA Agent", "status": "approved", "detail": "Criterios aprovados."},
        ],
        "summary": {"stories": len(SQUAD_BACKLOG), "decisions": len(decision_log), "approved": 3},
    }
    return deepcopy(LAST_SQUAD_RUN)


class Handler(BaseHTTPRequestHandler):
    def do_GET(self):
        try:
            path = urlparse(self.path).path
            if path == "/api/health":
                self.json({"status": "ok"})
            elif path == "/api/briefing":
                self.json({"briefing": default_briefing()})
            elif path == "/api/squad/latest":
                self.json(LAST_SQUAD_RUN or run_squad_observability(default_briefing()))
            elif path == "/api/nonconformities":
                self.json({"items": list_nonconformities()})
            elif path.startswith("/api/root-cause/"):
                self.json(analyze_root_cause(unquote(path.rsplit("/", 1)[-1])))
            elif path.startswith("/api/traceability/"):
                self.json(trace_lot(unquote(path.rsplit("/", 1)[-1])))
            else:
                self.static(path)
        except ValueError as exc:
            self.json({"error": str(exc)}, HTTPStatus.BAD_REQUEST)
        except KeyError as exc:
            self.json({"error": str(exc).strip("'")}, HTTPStatus.NOT_FOUND)

    def do_POST(self):
        try:
            path = urlparse(self.path).path
            length = int(self.headers.get("Content-Length", "0"))
            payload = json.loads(self.rfile.read(length).decode("utf-8")) if length else {}
            if path == "/api/squad/run":
                self.json(run_squad_observability(payload.get("briefing", "")))
                return
            if path != "/api/nonconformities":
                self.json({"error": "Rota nao encontrada."}, HTTPStatus.NOT_FOUND)
                return
            self.json(create_nonconformity(payload), HTTPStatus.CREATED)
        except ValueError as exc:
            self.json({"error": str(exc)}, HTTPStatus.BAD_REQUEST)

    def static(self, path):
        target = FRONTEND / ("index.html" if path in ("", "/") else path.lstrip("/"))
        if not target.exists():
            self.json({"error": "Arquivo nao encontrado."}, HTTPStatus.NOT_FOUND)
            return
        content_type = "text/css" if target.suffix == ".css" else "application/javascript" if target.suffix == ".js" else "text/html"
        body = target.read_bytes()
        self.send_response(HTTPStatus.OK)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def json(self, data, status=HTTPStatus.OK):
        body = json.dumps(data, ensure_ascii=False).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--port", type=int, default=8000)
    args = parser.parse_args()
    server = ThreadingHTTPServer(("127.0.0.1", args.port), Handler)
    print(f"Rivexx rodando em http://127.0.0.1:{args.port}")
    server.serve_forever()


if __name__ == "__main__":
    main()
