const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
function esc(value){return String(value??"").replace(/[&<>"']/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]))}
async function api(path,options){const response=await fetch(path,{headers:{"Content-Type":"application/json"},...options});const data=await response.json();if(!response.ok)throw Error(data.error||"Erro na requisicao.");return data}
function bindTabs(){$$("nav button").forEach((button)=>{button.onclick=()=>{$$(".tab").forEach((tab)=>tab.classList.remove("active"));$("#"+button.dataset.tab).classList.add("active")}})}
function renderSquad(run){$("#runStatus").textContent=`Status: ${run.status} | Run ${run.run_id}`;$("#runMetrics").innerHTML=`<div><strong>${esc(run.summary.stories)}</strong><span>stories</span></div><div><strong>${esc(run.summary.decisions)}</strong><span>decisoes Dev</span></div><div><strong>${esc(run.summary.approved)}</strong><span>aprovadas QA</span></div><p>${esc(run.enriched_brief)}</p>`;$("#conversationLog").innerHTML=run.communication_log.map((item)=>`<article class="log-item"><header>${esc(item.from_agent)} -> ${esc(item.to_agent)}</header><p>${esc(item.content)}</p></article>`).join("");$("#backlogLog").innerHTML=run.backlog.map((story)=>`<article class="log-item"><header>${esc(story.id)} - ${esc(story.title)}</header><p>${esc(story.description)}</p><small>${story.acceptance_criteria.map(esc).join(" | ")}</small></article>`).join("");$("#decisionLog").innerHTML=run.decision_log.map((decision)=>`<article class="log-item"><header>${esc(decision.story_id)}</header><p>${esc(decision.summary)}</p><small>${esc(decision.rationale)}</small><small>Arquivos: ${decision.files_changed.map(esc).join(", ")}</small></article>`).join("");$("#qaLog").innerHTML=run.qa_report.map((report)=>`<article class="log-item ${report.approved?"approved":"failed"}"><header>${esc(report.story_id)} - ${report.approved?"Aprovado":"Reprovado"}</header><p>${esc(report.evidence)}</p><small>${report.test_cases.map((test)=>`${esc(test.name)}: ${esc(test.result)}`).join(" | ")}</small></article>`).join("")}
async function loadBriefingConsole(){const briefing=await api("/api/briefing");$("#briefingInput").value=briefing.briefing;renderSquad(await api("/api/squad/latest"))}
async function runSquad(event){event.preventDefault();$("#runStatus").textContent="Rodando squad...";try{renderSquad(await api("/api/squad/run",{method:"POST",body:JSON.stringify({briefing:$("#briefingInput").value})}))}catch(error){$("#runStatus").textContent=error.message}}
async function loadRecords(){const data=await api("/api/nonconformities");$("#records").innerHTML=data.items.map((record)=>`<div class="card"><b>${esc(record.id)} - ${esc(record.lot_code)}</b><p>${esc(record.description)}</p><small>${esc(record.created_at)} | ${esc(record.responsible)} | ${esc(record.shift)} | ${esc(record.equipment)} | ${esc(record.line)}</small></div>`).join("");$("#recordSelect").innerHTML=data.items.map((record)=>`<option>${esc(record.id)}</option>`).join("");if(data.items[0])loadCause(data.items[0].id)}
async function loadCause(id){const data=await api("/api/root-cause/"+encodeURIComponent(id));$("#analysis").innerHTML=`<h2>5 porques</h2>${data.five_whys.map((item)=>`<div class="card">${esc(item)}</div>`).join("")}<h2>Causas sugeridas</h2>${data.suggested_causes.map((item)=>`<div class="card"><b>${esc(item.cause)}</b><p>${esc(item.evidence)}</p></div>`).join("")}<h2>Plano</h2><div class="grid">${data.action_plan.map((item)=>`<div class="card"><b>${esc(item.action)}</b><p>${esc(item.owner)} | ${esc(item.due)} | ${esc(item.status)}</p></div>`).join("")}</div>`}
async function submitNonconformity(event){event.preventDefault();try{const data=await api("/api/nonconformities",{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(event.target)))});$("#message").textContent=`${data.id} registrado.`;await loadRecords()}catch(error){$("#message").textContent=error.message}}
async function submitLot(event){event.preventDefault();try{const data=await api("/api/traceability/"+encodeURIComponent(new FormData(event.target).get("lot")));$("#trace").innerHTML=`<div class="card"><b>${esc(data.lot_code)}</b><p>${esc(data.raw_material)} | ${esc(data.supplier)}</p><p>${esc(data.equipment)} | turno ${esc(data.shift)} | ${data.operators.map(esc).join(", ")}</p><p>Correlatos: ${data.correlated_lots.map(esc).join(", ")}</p><p>Expedicao: ${data.shipments.map(esc).join(", ")}</p></div>`}catch(error){$("#trace").innerHTML=`<div class="card">${esc(error.message)}</div>`}}
function bindForms(){$("#briefingForm").onsubmit=runSquad;$("#form").onsubmit=submitNonconformity;$("#recordSelect").onchange=(event)=>loadCause(event.target.value);$("#lotForm").onsubmit=submitLot}
async function boot(){bindTabs();bindForms();await loadBriefingConsole();await loadRecords();$("#lotForm").dispatchEvent(new Event("submit"))}
boot().catch((error)=>{document.body.innerHTML=`<main class="shell"><section class="tab active">${esc(error.message)}</section></main>`});
